export const initialCards = [
    { title: "Robusnipe NFT Discoveries", image: "/pageone/nft1.svg" },
    { title: "Manga AI NFT Discoveries", image: "/pageone/nft2.svg" },
    { title: "Roburna NFT Discoveries", image: "/pageone/nft3.svg" },
    { title: "F4H NFT Discoveries", image: "/pageone/nft4.svg" },
];

export const additionalCards = [
    [
        { image: '/robusnipe/robo1.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo2.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo3.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo4.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo5.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo6.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo7.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo8.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo9.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo10.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo11.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/robusnipe/robo12.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
    ],
    [
        { image: '/manga-ai/manga1.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga2.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga4.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga5.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga3.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga6.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga7.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga8.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga9.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga10.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga11.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/manga-ai/manga12.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
    ],
    [
        { image: '/roburna/robuna1.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna2.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna4.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna5.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna3.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna6.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna7.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna8.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna9.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna10.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna11.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/roburna/robuna12.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
    ],
    [
        { image: '/f4h/f4h1.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h2.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h4.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h5.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h3.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h7.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h8.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h9.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h10.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h11.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h12.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
        { image: '/f4h/f4h13.svg', title: 'Ryi Unity Campaign', description: 'Exclusive NFT for Arborswap - RYI Unity Campaign participants' },
    ],
];
